-- Baseline of the CUS schema (stage 0, §13).
--
-- Business tables (subjects, consents, forms, journals) are introduced by the migrations of
-- stages 1 and later. This baseline only creates the lock table required by ShedLock (§4),
-- so that the scheduled jobs of stages 3, 6 and 8 have their storage from the first migration on
-- and every environment starts from an identical, non-empty schema.
--
-- Conventions fixed here and followed by every later migration (§6):
--   * primary keys are UUID values generated by the application;
--   * every timestamp is timestamptz and is stored in UTC;
--   * only SQL that is compatible with PostgreSQL 15/16 and Postgres Pro Standard is used.

CREATE TABLE shedlock (
    name       VARCHAR(64)  NOT NULL,
    lock_until TIMESTAMPTZ  NOT NULL,
    locked_at  TIMESTAMPTZ  NOT NULL,
    locked_by  VARCHAR(255) NOT NULL,
    CONSTRAINT shedlock_pkey PRIMARY KEY (name)
);

COMMENT ON TABLE shedlock IS 'ShedLock locks that keep scheduled jobs single-writer across instances (NFR-2)';
