-- Stage 1 (§13): IAM, dictionaries, subjects, audit.
--
-- Conventions (§6): UUID primary keys generated by the application, timestamptz everywhere (UTC in the
-- database), mutable entities carry created_at/created_by/updated_at/updated_by/version, dictionaries are
-- deactivated instead of deleted. Single operator per installation (ADR-0015): no tenant column.

-- ---------------------------------------------------------------------------------------------------
-- IAM (FR-11.1, FR-11.2)
-- ---------------------------------------------------------------------------------------------------

CREATE TABLE app_role (
    id          UUID         NOT NULL,
    code        VARCHAR(32)  NOT NULL,
    name_ru     VARCHAR(128) NOT NULL,
    description TEXT,
    CONSTRAINT app_role_pkey PRIMARY KEY (id),
    CONSTRAINT app_role_code_uk UNIQUE (code)
);

COMMENT ON TABLE app_role IS 'Роли пользователей, матрица прав — Приложение E ТЗ';

CREATE TABLE app_user (
    id                     UUID         NOT NULL,
    login                  VARCHAR(128) NOT NULL,
    password_hash          VARCHAR(255) NOT NULL,
    full_name              VARCHAR(255) NOT NULL,
    email                  VARCHAR(255),
    is_active              BOOLEAN      NOT NULL DEFAULT TRUE,
    -- FR-11.1: protection of /auth/login against brute force. Kept in the database rather than in
    -- memory so that the counter survives a restart and is shared by all instances (NFR-2).
    failed_login_attempts  INTEGER      NOT NULL DEFAULT 0,
    locked_until           TIMESTAMPTZ,
    last_login_at          TIMESTAMPTZ,
    created_at             TIMESTAMPTZ  NOT NULL,
    created_by             VARCHAR(128),
    updated_at             TIMESTAMPTZ  NOT NULL,
    updated_by             VARCHAR(128),
    version                BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT app_user_pkey PRIMARY KEY (id),
    CONSTRAINT app_user_login_uk UNIQUE (login)
);

CREATE TABLE app_user_role (
    user_id UUID NOT NULL,
    role_id UUID NOT NULL,
    CONSTRAINT app_user_role_pkey PRIMARY KEY (user_id, role_id),
    CONSTRAINT app_user_role_user_fk FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT app_user_role_role_fk FOREIGN KEY (role_id) REFERENCES app_role (id)
);

CREATE INDEX app_user_role_role_idx ON app_user_role (role_id);

-- ---------------------------------------------------------------------------------------------------
-- Operator settings (FR-11.3)
-- ---------------------------------------------------------------------------------------------------

CREATE TABLE operator_settings (
    key        VARCHAR(128) NOT NULL,
    value      TEXT,
    updated_at TIMESTAMPTZ  NOT NULL,
    updated_by VARCHAR(128),
    CONSTRAINT operator_settings_pkey PRIMARY KEY (key)
);

COMMENT ON TABLE operator_settings IS 'Реквизиты оператора, контакт DPO, пороги, таймзона (FR-11.3)';

-- ---------------------------------------------------------------------------------------------------
-- Dictionaries (FR-1.1, FR-11.4)
-- ---------------------------------------------------------------------------------------------------

CREATE TABLE pdn_category (
    id           UUID         NOT NULL,
    code         VARCHAR(64)  NOT NULL,
    name_ru      VARCHAR(255) NOT NULL,
    is_special   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_biometric BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pdn_category_pkey PRIMARY KEY (id),
    CONSTRAINT pdn_category_code_uk UNIQUE (code)
);

COMMENT ON COLUMN pdn_category.is_special IS 'Специальная категория ПДн (ст. 10 152-ФЗ)';

CREATE TABLE consent_type (
    id                   UUID         NOT NULL,
    code                 VARCHAR(64)  NOT NULL,
    name_ru              VARCHAR(255) NOT NULL,
    description          TEXT,
    category             VARCHAR(32)  NOT NULL,
    channels             TEXT[]       NOT NULL DEFAULT '{}',
    requires_third_party BOOLEAN      NOT NULL DEFAULT FALSE,
    -- ISO-8601 duration, NULL means "до отзыва" (FR-4.3)
    default_validity     VARCHAR(32),
    depends_on_type_id   UUID,
    business_significant BOOLEAN      NOT NULL DEFAULT TRUE,
    is_active            BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order           INTEGER      NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ  NOT NULL,
    created_by           VARCHAR(128),
    updated_at           TIMESTAMPTZ  NOT NULL,
    updated_by           VARCHAR(128),
    version              BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT consent_type_pkey PRIMARY KEY (id),
    CONSTRAINT consent_type_code_uk UNIQUE (code),
    CONSTRAINT consent_type_depends_on_fk FOREIGN KEY (depends_on_type_id) REFERENCES consent_type (id)
);

COMMENT ON COLUMN consent_type.depends_on_type_id IS 'Каскадный отзыв: отзыв базового типа отзывает зависимые (FR-8.4)';

CREATE INDEX consent_type_active_idx ON consent_type (is_active, sort_order);

-- ---------------------------------------------------------------------------------------------------
-- Third parties (FR-7.1)
-- ---------------------------------------------------------------------------------------------------

CREATE TABLE third_party (
    id                      UUID         NOT NULL,
    name                    VARCHAR(512) NOT NULL,
    short_name              VARCHAR(255),
    inn                     VARCHAR(12)  NOT NULL,
    ogrn                    VARCHAR(15),
    address                 TEXT         NOT NULL,
    role                    VARCHAR(32)  NOT NULL,
    contract_number         VARCHAR(128),
    contract_date           DATE,
    contract_valid_until    DATE,
    allowed_pdn_categories  TEXT[]       NOT NULL DEFAULT '{}',
    contact_email           VARCHAR(255),
    is_active               BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMPTZ  NOT NULL,
    created_by              VARCHAR(128),
    updated_at              TIMESTAMPTZ  NOT NULL,
    updated_by              VARCHAR(128),
    version                 BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT third_party_pkey PRIMARY KEY (id),
    -- FR-4.5 matches third parties by ИНН during import, so it has to be unique
    CONSTRAINT third_party_inn_uk UNIQUE (inn)
);

CREATE INDEX third_party_contract_idx ON third_party (contract_valid_until) WHERE is_active;

-- ---------------------------------------------------------------------------------------------------
-- Subjects (FR-5.2)
-- ---------------------------------------------------------------------------------------------------

CREATE TABLE subject (
    id          UUID         NOT NULL,
    external_id VARCHAR(128) NOT NULL,
    last_name   VARCHAR(128) NOT NULL,
    first_name  VARCHAR(128) NOT NULL,
    middle_name VARCHAR(128),
    birth_date  DATE,
    created_at  TIMESTAMPTZ  NOT NULL,
    created_by  VARCHAR(128),
    updated_at  TIMESTAMPTZ  NOT NULL,
    updated_by  VARCHAR(128),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT subject_pkey PRIMARY KEY (id),
    CONSTRAINT subject_external_id_uk UNIQUE (external_id)
);

COMMENT ON TABLE subject IS 'In consensu не мастер-система по клиентам: хранится минимально необходимый состав (§6)';

-- Prefix search over the full name (FR-5.2, минимум 3 символа). text_pattern_ops makes LIKE 'префикс%'
-- index-friendly regardless of the database collation.
CREATE INDEX subject_full_name_prefix_idx ON subject
    (lower(last_name || ' ' || first_name || ' ' || coalesce(middle_name, '')) text_pattern_ops);

CREATE TABLE subject_contact (
    id               UUID         NOT NULL,
    subject_id       UUID         NOT NULL,
    type             VARCHAR(32)  NOT NULL,
    value            VARCHAR(512) NOT NULL,
    -- E.164 for phones, lowercase for e-mail (§6)
    value_normalized VARCHAR(512) NOT NULL,
    is_primary       BOOLEAN      NOT NULL DEFAULT FALSE,
    valid_from       TIMESTAMPTZ,
    valid_to         TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL,
    created_by       VARCHAR(128),
    updated_at       TIMESTAMPTZ  NOT NULL,
    updated_by       VARCHAR(128),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT subject_contact_pkey PRIMARY KEY (id),
    CONSTRAINT subject_contact_subject_fk FOREIGN KEY (subject_id) REFERENCES subject (id) ON DELETE CASCADE
);

-- No uniqueness across subjects on purpose (§6): a family may share a phone number.
CREATE INDEX subject_contact_lookup_idx ON subject_contact (type, value_normalized);
CREATE INDEX subject_contact_subject_idx ON subject_contact (subject_id);

-- ---------------------------------------------------------------------------------------------------
-- Audit (FR-10.1, FR-10.2, FR-10.5)
-- ---------------------------------------------------------------------------------------------------

CREATE TABLE audit_event (
    id             BIGSERIAL    NOT NULL,
    aggregate_type VARCHAR(64)  NOT NULL,
    aggregate_id   VARCHAR(128) NOT NULL,
    subject_id     UUID,
    event_type     VARCHAR(64)  NOT NULL,
    occurred_at    TIMESTAMPTZ  NOT NULL,
    actor_type     VARCHAR(32)  NOT NULL,
    actor_id       VARCHAR(128),
    payload        JSONB        NOT NULL,
    -- Hash chain per aggregate: hash = SHA-256(prev_hash + canonical event JSON), see ADR-0017
    prev_hash      VARCHAR(64),
    hash           VARCHAR(64)  NOT NULL,
    CONSTRAINT audit_event_pkey PRIMARY KEY (id)
);

CREATE INDEX audit_event_aggregate_idx ON audit_event (aggregate_type, aggregate_id, id);
CREATE INDEX audit_event_occurred_idx ON audit_event (occurred_at);
CREATE INDEX audit_event_type_idx ON audit_event (event_type, occurred_at);
CREATE INDEX audit_event_subject_idx ON audit_event (subject_id, occurred_at) WHERE subject_id IS NOT NULL;

CREATE TABLE audit_anchor (
    day          DATE        NOT NULL,
    events_count BIGINT      NOT NULL,
    day_hash     VARCHAR(64) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL,
    CONSTRAINT audit_anchor_pkey PRIMARY KEY (day)
);

COMMENT ON TABLE audit_anchor IS 'Ежедневный «якорь» — хеш всех событий дня для внешней фиксации (FR-10.1)';

CREATE TABLE pdn_access_log (
    id             BIGSERIAL    NOT NULL,
    user_id        UUID,
    endpoint       VARCHAR(255) NOT NULL,
    subject_id     UUID,
    subjects_count INTEGER      NOT NULL DEFAULT 1,
    request_id     VARCHAR(64),
    occurred_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT pdn_access_log_pkey PRIMARY KEY (id)
);

CREATE INDEX pdn_access_log_occurred_idx ON pdn_access_log (occurred_at);
CREATE INDEX pdn_access_log_user_idx ON pdn_access_log (user_id, occurred_at);
CREATE INDEX pdn_access_log_subject_idx ON pdn_access_log (subject_id, occurred_at) WHERE subject_id IS NOT NULL;

-- ---------------------------------------------------------------------------------------------------
-- FR-10.2: journals are append-only.
--
-- First line of defence, always active: a trigger that refuses UPDATE and DELETE. Second line, active
-- when the operator runs the application under a role of its own: that role loses UPDATE and DELETE on
-- the journals, while migrations keep running under the owner. The role name comes from the Flyway
-- placeholder `appRole` (spring.flyway.placeholders.appRole / INCONSENSU_DB_APP_ROLE); when it is empty or
-- equals the migration user, only the trigger protects the tables.
-- ---------------------------------------------------------------------------------------------------

CREATE FUNCTION cus_reject_journal_modification() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'Таблица % доступна только для добавления записей (FR-10.2)', TG_TABLE_NAME
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_event_append_only
    BEFORE UPDATE OR DELETE ON audit_event
    FOR EACH STATEMENT EXECUTE FUNCTION cus_reject_journal_modification();

CREATE TRIGGER audit_anchor_append_only
    BEFORE UPDATE OR DELETE ON audit_anchor
    FOR EACH STATEMENT EXECUTE FUNCTION cus_reject_journal_modification();

CREATE TRIGGER pdn_access_log_append_only
    BEFORE UPDATE OR DELETE ON pdn_access_log
    FOR EACH STATEMENT EXECUTE FUNCTION cus_reject_journal_modification();

DO $$
DECLARE
    application_role TEXT := '${appRole}';
BEGIN
    IF application_role <> '' AND application_role <> current_user
        AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = application_role) THEN
        EXECUTE format('REVOKE UPDATE, DELETE ON audit_event, audit_anchor, pdn_access_log FROM %I',
                       application_role);
    END IF;
END;
$$;
